import { Element, SystemType } from './types';

function createBaseElement(
  name: string,
  system: SystemType,
  index: number,
  description: string
): Element {
  return {
    id: `${system}-${index}`,
    name,
    system,
    description,
  };
}

export const BASE_ELEMENTS: Element[] = [
  // Emotions (14 elements)
  createBaseElement('Joy', 'emotions', 0, 'Pure, unfiltered happiness that lights up everything it touches. The foundation of connection and celebration.'),
  createBaseElement('Fear', 'emotions', 1, 'The primal instinct that keeps us alive, but can also cage us. A powerful motivator wrapped in uncertainty.'),
  createBaseElement('Anger', 'emotions', 2, 'Fire in the veins that demands justice and change. A force that can destroy or transform.'),
  createBaseElement('Desire', 'emotions', 3, 'The yearning that pulls us forward, promising fulfillment. What we want reveals who we are.'),
  createBaseElement('Shame', 'emotions', 4, 'The weight of not being enough, carried in silence. A shadow that shapes how we hide ourselves.'),
  createBaseElement('Pride', 'emotions', 5, 'The armor of self-worth that can become a prison. Confidence teetering on the edge of arrogance.'),
  createBaseElement('Loneliness', 'emotions', 6, 'The ache of disconnection in a crowded room. An emptiness that hungers for belonging.'),
  createBaseElement('Hope', 'emotions', 7, 'The stubborn belief that tomorrow could be different. A fragile light that refuses to die.'),
  createBaseElement('Grief', 'emotions', 8, 'The price of having loved deeply. An ocean of loss that reshapes the shoreline of who you are.'),
  createBaseElement('Wonder', 'emotions', 9, 'Eyes wide at the impossible made real. The spark that turns the mundane into magic.'),
  createBaseElement('Envy', 'emotions', 10, 'The poison of wanting what others have. A hunger that feeds on comparison and withers contentment.'),
  createBaseElement('Guilt', 'emotions', 11, 'The echo of choices that can\'t be unmade. A debt paid in sleepless nights and what-ifs.'),
  createBaseElement('Contentment', 'emotions', 12, 'The quiet satisfaction of enough. Peace found not in having everything, but in wanting what you have.'),
  createBaseElement('Despair', 'emotions', 13, 'Hope\'s dark mirror, where tomorrow promises only more of today. The belief that nothing will ever change.'),

  // Story Particles (14 elements)
  createBaseElement('A glance', 'story-particles', 0, 'A fleeting moment of eye contact that says everything words cannot. Universes collide in a single look.'),
  createBaseElement('A door', 'story-particles', 1, 'The threshold between worlds, between choices. Every door holds both an exit and an entrance.'),
  createBaseElement('A lie', 'story-particles', 2, 'A small untruth that grows roots. What starts as protection often becomes a cage.'),
  createBaseElement('Rain', 'story-particles', 3, 'The sky weeping or washing clean, depending on who you ask. Nature\'s way of making everything feel more dramatic.'),
  createBaseElement('A name', 'story-particles', 4, 'Identity wrapped in syllables, carrying history and expectation. To name something is to give it power.'),
  createBaseElement('Silence', 'story-particles', 5, 'The absence of sound that speaks louder than words. What isn\'t said often matters most.'),
  createBaseElement('A scar', 'story-particles', 6, 'Proof that something wounded you and you survived. Every mark tells a story written in flesh.'),
  createBaseElement('Running', 'story-particles', 7, 'Flight toward or away from something. Movement as instinct, as desperation, as freedom.'),
  createBaseElement('A letter', 'story-particles', 8, 'Words frozen in time, meant for one set of eyes. Ink that can bridge distance or burn bridges.'),
  createBaseElement('Blood', 'story-particles', 9, 'Life\'s currency spilled. The stain that marks where everything changed, witness to violence or sacrifice.'),
  createBaseElement('A promise', 'story-particles', 10, 'Spoken vows that bind futures. The weight of words meant to be kept, until they\'re broken.'),
  createBaseElement('Footsteps', 'story-particles', 11, 'The rhythm of approach or departure. Someone coming closer or walking away, either way your heart races.'),
  createBaseElement('A mirror', 'story-particles', 12, 'Truth reflected back, unflinching. The confrontation with who you are versus who you pretend to be.'),
  createBaseElement('Fire', 'story-particles', 13, 'Warmth and destruction dancing together. The force that cooks meals and razes kingdoms, depending on who holds the match.'),

  // Characteristics (14 elements)
  createBaseElement('Ambitious', 'characteristics', 0, 'Driven by visions of what could be, willing to sacrifice for the climb. Success is oxygen.'),
  createBaseElement('Wounded', 'characteristics', 1, 'Carrying pain that shaped them, for better or worse. Past trauma colors every present moment.'),
  createBaseElement('Cheerful', 'characteristics', 2, 'Radiating optimism that could be genuine or armor. Brightness that either heals or deflects.'),
  createBaseElement('Secretive', 'characteristics', 3, 'Guarding truths behind practiced smiles and careful words. Privacy is survival.'),
  createBaseElement('Loyal', 'characteristics', 4, 'Steadfast to a fault, standing beside chosen people through storms. Devotion as both strength and weakness.'),
  createBaseElement('Rebellious', 'characteristics', 5, 'Challenging authority and breaking rules on principle. Freedom fighter or troublemaker, depending on perspective.'),
  createBaseElement('Careful', 'characteristics', 6, 'Weighing every risk, planning three moves ahead. Safety through control.'),
  createBaseElement('Wild', 'characteristics', 7, 'Untamed and unpredictable, following instinct over reason. Chaos as a form of honesty.'),
  createBaseElement('Cynical', 'characteristics', 8, 'Seeing through illusions to the rot beneath. The wisdom of having been disappointed too many times.'),
  createBaseElement('Gentle', 'characteristics', 9, 'Moving through the world with soft hands and softer words. Strength that knows it doesn\'t need to prove itself.'),
  createBaseElement('Ruthless', 'characteristics', 10, 'Willing to do what others won\'t for what matters most. Morality is negotiable; victory is not.'),
  createBaseElement('Naive', 'characteristics', 11, 'Believing the best of people and worlds not yet cruel enough to teach otherwise. Innocence as vulnerability and power.'),
  createBaseElement('Haunted', 'characteristics', 12, 'Carrying ghosts that won\'t rest. The past isn\'t behind them—it walks beside them, whispering.'),
  createBaseElement('Charming', 'characteristics', 13, 'Wielding charisma like a weapon or a gift. The magnetism that draws people in, for better or worse.'),

  // Tropes (14 elements)
  createBaseElement('Fake Dating', 'tropes', 0, 'Pretending to be in love for practical reasons. Feelings that were supposed to stay fake rarely do.'),
  createBaseElement('Enemy', 'tropes', 1, 'Opposition and conflict that defines both sides. The line between enemy and obsession is razor-thin.'),
  createBaseElement('Amnesia', 'tropes', 2, 'The past erased, identity rebuilt from fragments. Who are you when you can\'t remember?'),
  createBaseElement('Prophecy', 'tropes', 3, 'Destiny written before birth, fate as a cage or calling. Fighting or fulfilling what was foretold.'),
  createBaseElement('Heist', 'tropes', 4, 'The elaborate plan, the perfect team, the impossible target. Everything depends on timing.'),
  createBaseElement('Masquerade', 'tropes', 5, 'Hidden faces and hidden motives, dancing through deception. Everyone is pretending to be someone else.'),
  createBaseElement('Deadline', 'tropes', 6, 'Time running out, pressure mounting with every tick. The clock becomes the enemy.'),
  createBaseElement('Secret Identity', 'tropes', 7, 'Living two lives, wearing two faces. The exhaustion of never being fully yourself.'),
  createBaseElement('Chosen One', 'tropes', 8, 'Marked by destiny, burdened by expectation. The weight of being special when you just wanted to be normal.'),
  createBaseElement('Mentor Dies', 'tropes', 9, 'The wise guide falls, leaving the student alone too soon. Learning to fly when the nest burns beneath you.'),
  createBaseElement('Love Triangle', 'tropes', 10, 'Three hearts tangled in impossible geometry. Someone\'s getting hurt, and it might be everyone.'),
  createBaseElement('Redemption Arc', 'tropes', 11, 'Climbing out of darkness toward the light. The long road from villain to hero, paved with hard choices.'),
  createBaseElement('Mistaken Identity', 'tropes', 12, 'Being someone you\'re not, accidentally or on purpose. The lies that snowball until you forget who you were.'),
  createBaseElement('Underdog', 'tropes', 13, 'The one no one believes in, fighting against impossible odds. Victory tastes sweeter when everyone expected you to fail.'),

  // Sensory (14 elements)
  createBaseElement('Smoke', 'sensory', 0, 'Curling wisps that obscure and reveal, carrying scent memory. The ghost of fire.'),
  createBaseElement('Silk', 'sensory', 1, 'Luxury that whispers against skin, promise of wealth or seduction. Softness hiding strength.'),
  createBaseElement('Iron', 'sensory', 2, 'The taste of blood, the weight of chains, the strength of will. Cold, hard reality.'),
  createBaseElement('Honey', 'sensory', 3, 'Golden sweetness, slow and rich and sticky. Comfort that can trap.'),
  createBaseElement('Thunder', 'sensory', 4, 'Sky-splitting roar that shakes bones and announces power. The warning before the strike.'),
  createBaseElement('Shadow', 'sensory', 5, 'Absence of light where things hide. Darkness as shelter or threat.'),
  createBaseElement('Salt', 'sensory', 6, 'Tears, ocean, earth. The taste of life preserved or wounds opened.'),
  createBaseElement('Starlight', 'sensory', 7, 'Ancient light touching skin, distant and cold but beautiful. Hope from dead things.'),
  createBaseElement('Frost', 'sensory', 8, 'Ice crystals painting the world in stillness. Beauty that burns, cold that preserves and kills.'),
  createBaseElement('Velvet', 'sensory', 9, 'Decadence in texture, soft as sin. The touch of luxury, of theater curtains, of secrets kept in plush darkness.'),
  createBaseElement('Ash', 'sensory', 10, 'What remains when everything burns away. Gray dust of endings, settling like snow over what used to be.'),
  createBaseElement('Whisper', 'sensory', 11, 'Sound that demands you lean closer. Secrets shared breath-close, conspiracies born in hushed tones.'),
  createBaseElement('Crimson', 'sensory', 12, 'The color of passion and violence. Red that paints lips, roses, and battlefields with equal intensity.'),
  createBaseElement('Marble', 'sensory', 13, 'Stone polished to perfection, cold and eternal. The touch of monuments, of wealth, of things built to outlast you.'),

  // Momentum (14 elements)
  createBaseElement('Chase', 'momentum', 0, 'Pursuit with everything on the line, hunter and hunted locked in motion. Speed becomes survival.'),
  createBaseElement('Hide', 'momentum', 1, 'Disappearing into shadows, becoming invisible, holding breath. Safety in stillness and silence.'),
  createBaseElement('Reveal', 'momentum', 2, 'The moment truth comes to light, secrets exposed. Everything changes when seen.'),
  createBaseElement('Betray', 'momentum', 3, 'The knife in the back from a trusted hand. Trust shattered becomes a weapon.'),
  createBaseElement('Protect', 'momentum', 4, 'Standing between loved ones and danger, shield raised. Love expressed through sacrifice.'),
  createBaseElement('Destroy', 'momentum', 5, 'Tearing down what was built, burning bridges, breaking bonds. Sometimes creation requires destruction.'),
  createBaseElement('Create', 'momentum', 6, 'Building something from nothing, breathing life into ideas. The power to shape reality.'),
  createBaseElement('Wait', 'momentum', 7, 'Patience as strategy, stillness as strength. Sometimes the hardest action is inaction.'),
  createBaseElement('Flee', 'momentum', 8, 'Running from what you can\'t face. Survival instinct overriding pride, shame trailing like a shadow.'),
  createBaseElement('Confess', 'momentum', 9, 'Speaking truth that\'s been locked inside too long. The relief and terror of being finally, fully known.'),
  createBaseElement('Surrender', 'momentum', 10, 'Laying down arms, admitting defeat or choosing peace. The strength it takes to stop fighting.'),
  createBaseElement('Demand', 'momentum', 11, 'Taking up space, claiming what\'s yours. The force of wanting something enough to refuse silence.'),
  createBaseElement('Forgive', 'momentum', 12, 'Releasing the weight of what was done. A gift given to them, to you, or maybe both.'),
  createBaseElement('Remember', 'momentum', 13, 'Pulling the past into the present, keeping it alive. Memory as weapon, as anchor, as treasure.'),

  // Theme (14 elements)
  createBaseElement('Power corrupts', 'theme', 0, 'The slow rot of authority, how control changes those who wield it. Good intentions paved into tyranny.'),
  createBaseElement('Love conquers all', 'theme', 1, 'The belief that connection transcends every barrier. Hope wearing the face of devotion.'),
  createBaseElement('Coming of age', 'theme', 2, 'Innocence lost, wisdom gained. The painful bridge between who you were and who you must become.'),
  createBaseElement('Revenge', 'theme', 3, 'Justice twisted by hurt, the cycle of pain feeding itself. An eye for an eye until everyone is blind.'),
  createBaseElement('Redemption', 'theme', 4, 'The possibility of being more than your worst moment. Second chances and the work they demand.'),
  createBaseElement('Isolation', 'theme', 5, 'Cut off from the world, alone with your thoughts. Solitude as prison, as sanctuary, as test.'),
  createBaseElement('Identity', 'theme', 6, 'The question of who you are beneath the masks. Self-discovery as revolution.'),
  createBaseElement('Sacrifice', 'theme', 7, 'What you give up for what matters more. Love measured in what you\'re willing to lose.'),
  createBaseElement('Survival', 'theme', 8, 'The will to keep breathing when everything says stop. Endurance as defiance.'),
  createBaseElement('Freedom vs. security', 'theme', 9, 'The eternal trade-off between safety and autonomy. Comfort as cage, risk as liberation.'),
  createBaseElement('Nature vs. nurture', 'theme', 10, 'Born or made, genes or choices. The debate over what writes our story.'),
  createBaseElement('Good vs. evil', 'theme', 11, 'The eternal struggle between light and dark. Moral certainty in an ambiguous world.'),
  createBaseElement('Man vs. nature', 'theme', 12, 'The wild as adversary, as teacher, as mirror. Humanity humbled by forces beyond control.'),
  createBaseElement('The American Dream', 'theme', 13, 'Success as salvation, prosperity as birthright. The promise and the price of wanting more.'),

  // Relationship (14 elements)
  createBaseElement('Mentor-student', 'relationship', 0, 'Wisdom passed down, potential unlocked. Trust built on guidance and growth.'),
  createBaseElement('Enemies to lovers', 'relationship', 1, 'Hate as the first draft of passion. Walls crumbling into bridges.'),
  createBaseElement('Found family', 'relationship', 2, 'Bonds chosen, not given. Love that transcends blood.'),
  createBaseElement('Unrequited love', 'relationship', 3, 'Wanting someone who doesn\'t want you back. Hope bleeding into heartbreak.'),
  createBaseElement('Siblings rivalry', 'relationship', 4, 'Competition born from sharing the same cradle. Love tangled with resentment.'),
  createBaseElement('Betrayed friendship', 'relationship', 5, 'Trust shattered by someone who knew you best. Intimacy weaponized.'),
  createBaseElement('Star-crossed lovers', 'relationship', 6, 'Love forbidden by fate, family, or fortune. Desire stronger than consequences.'),
  createBaseElement('Parent-child bond', 'relationship', 7, 'The first love, the deepest debt. Protection and suffocation in equal measure.'),
  createBaseElement('Master-servant', 'relationship', 8, 'Power imbalance codified, loyalty purchased or coerced. Duty as devotion, as prison.'),
  createBaseElement('Partners in crime', 'relationship', 9, 'Shared secrets, shared risks. Trust forged in the fire of breaking rules together.'),
  createBaseElement('Rivals', 'relationship', 10, 'Competition that pushes both higher. Respect wrapped in opposition.'),
  createBaseElement('Toxic codependency', 'relationship', 11, 'Need masquerading as love. Two people destroying each other slowly.'),
  createBaseElement('Distant relatives', 'relationship', 12, 'Blood ties stretched thin by time and distance. Obligation without intimacy.'),
  createBaseElement('Unlikely allies', 'relationship', 13, 'Cooperation despite differences. Necessity breeding strange partnerships.'),

  // Beat (14 elements)
  createBaseElement('The call to adventure', 'beat', 0, 'An invitation to leave the ordinary behind. The moment everything could change.'),
  createBaseElement('Crossing the threshold', 'beat', 1, 'Stepping into the unknown, no turning back. The point of no return.'),
  createBaseElement('Meeting the mentor', 'beat', 2, 'Wisdom appears when the student is ready. The guide who lights the path.'),
  createBaseElement('The midpoint reversal', 'beat', 3, 'Everything you thought you knew was wrong. The pivot that changes the game.'),
  createBaseElement('All is lost', 'beat', 4, 'The darkest moment, defeat seeming certain. Rock bottom before the climb.'),
  createBaseElement('The final confrontation', 'beat', 5, 'Face to face with the ultimate challenge. Everything has led to this.'),
  createBaseElement('The revelation', 'beat', 6, 'Truth unveiled, secrets exposed. The moment that recontextualizes everything.'),
  createBaseElement('The sacrifice', 'beat', 7, 'Giving up what you treasure for what matters more. Love or duty demanding a price.'),
  createBaseElement('The reunion', 'beat', 8, 'Coming back together after being torn apart. Joy tinged with all that\'s changed.'),
  createBaseElement('The first kiss', 'beat', 9, 'The moment when possibility becomes reality. Crossing from wanting to having.'),
  createBaseElement('The betrayal', 'beat', 10, 'Trust broken by someone who had it completely. The knife from the inside.'),
  createBaseElement('The training montage', 'beat', 11, 'Transformation through repetition and sweat. Becoming capable of what seemed impossible.'),
  createBaseElement('The ticking clock', 'beat', 12, 'Time running out, pressure mounting. Every second matters now.'),
  createBaseElement('The unexpected ally', 'beat', 13, 'Help from the last person you\'d expect. Enemies becoming necessary friends.'),

  // === BOOK-INSPIRED ELEMENTS (540 total) ===

  // THE LORD OF THE RINGS - Frodo
  createBaseElement('Burden-weary resolve', 'emotions', 100, 'Carrying weight that grows heavier with each step forward.'),
  createBaseElement('Fading light of hope', 'story-particles', 100, 'A candle fighting against encroaching darkness.'),
  createBaseElement('Quiet determination', 'characteristics', 100, 'Strength that doesn\'t shout, power in persistence.'),
  createBaseElement('Reluctant hero', 'tropes', 100, 'Never asked for greatness, rose to meet it anyway.'),
  createBaseElement('Ring-weight on finger', 'sensory', 100, 'Cold metal growing heavier, whispering corruption.'),
  createBaseElement('Journey onward despite doubt', 'momentum', 100, 'One foot in front of the other when purpose wavers.'),
  createBaseElement('Corruption vs. innocence', 'theme', 100, 'How power tests the pure-hearted.'),
  createBaseElement('Loyal companion bond', 'relationship', 100, 'Friendship that carries you when you can\'t walk.'),
  createBaseElement('Accepting the quest', 'beat', 100, 'The moment of saying yes to an impossible task.'),

  // THE LORD OF THE RINGS - Gollum
  createBaseElement('Obsessive craving', 'emotions', 101, 'Want that has devoured everything else you were.'),
  createBaseElement('Precious thing lost', 'story-particles', 101, 'What you had and lost, defining you forever.'),
  createBaseElement('Split personality', 'characteristics', 101, 'Two souls warring in one broken body.'),
  createBaseElement('Tragic corruption', 'tropes', 101, 'What you were before darkness took you.'),
  createBaseElement('Wet cave echoes', 'sensory', 101, 'Dripping darkness and the sound of your own voice.'),
  createBaseElement('Slither and creep', 'momentum', 101, 'Moving in shadows, avoiding light and truth.'),
  createBaseElement('Addiction destroys', 'theme', 101, 'How desire can hollow you out completely.'),
  createBaseElement('Master-slave devotion', 'relationship', 101, 'Serving what you hate, loving what destroys you.'),
  createBaseElement('The fall from grace', 'beat', 101, 'Seeing what someone was before corruption.'),

  // THE LORD OF THE RINGS - The Shire
  createBaseElement('Gentle contentment', 'emotions', 102, 'Peace in simple things, joy in routine.'),
  createBaseElement('Rolling green hills', 'story-particles', 102, 'Home as a landscape of memory.'),
  createBaseElement('Provincial innocence', 'characteristics', 102, 'Sheltered from the darkness beyond your borders.'),
  createBaseElement('Idyllic homeland', 'tropes', 102, 'The perfect place you had to leave behind.'),
  createBaseElement('Pipe-smoke and ale', 'sensory', 102, 'Comfort in familiar smells and tastes.'),
  createBaseElement('Leaving home behind', 'momentum', 102, 'The first step away from everything safe.'),
  createBaseElement('Loss of innocence', 'theme', 102, 'Home can\'t stay untouched by your journey.'),
  createBaseElement('Childhood friends bond', 'relationship', 102, 'Those who knew you before the world changed you.'),
  createBaseElement('Departing the ordinary', 'beat', 102, 'Walking out your door into destiny.'),

  // THE LORD OF THE RINGS - Mordor
  createBaseElement('Crushing despair', 'emotions', 103, 'Hope crushed under shadow and ash.'),
  createBaseElement('Volcanic wasteland', 'story-particles', 103, 'Land where nothing grows, only destruction.'),
  createBaseElement('Absolute evil', 'characteristics', 103, 'Darkness made manifest, concentrated malice.'),
  createBaseElement('Dark lord\'s domain', 'tropes', 103, 'The fortress of ultimate evil.'),
  createBaseElement('Sulfur and burning', 'sensory', 103, 'Air that scorches lungs, ash that chokes.'),
  createBaseElement('Trudging toward doom', 'momentum', 103, 'Walking willingly into the heart of darkness.'),
  createBaseElement('Sacrifice for the greater good', 'theme', 103, 'One must be destroyed to save all.'),
  createBaseElement('Enemy territory alliance', 'relationship', 103, 'Trusting unlikely guides through hell.'),
  createBaseElement('Approaching the abyss', 'beat', 103, 'The final stretch to the point of no return.'),

  // THE LORD OF THE RINGS - The One Ring
  createBaseElement('Magnetic temptation', 'emotions', 104, 'Want so strong it feels like need.'),
  createBaseElement('Cursed artifact', 'story-particles', 104, 'Power that corrupts all who touch it.'),
  createBaseElement('Corruptive influence', 'characteristics', 104, 'Slowly poisoning everyone around it.'),
  createBaseElement('McGuffin of doom', 'tropes', 104, 'The object everyone wants that will destroy them.'),
  createBaseElement('Cold golden weight', 'sensory', 104, 'Beautiful metal that feels wrong to touch.'),
  createBaseElement('Succumbing to power', 'momentum', 104, 'Gradual surrender to what promises strength.'),
  createBaseElement('Power corrupts absolutely', 'theme', 104, 'How absolute power destroys absolutely.'),
  createBaseElement('Burden-bearer and burden', 'relationship', 104, 'Tied to what you must carry and destroy.'),
  createBaseElement('Claiming the prize', 'beat', 104, 'The moment of grasping what you shouldn\'t.'),

  // THE LORD OF THE RINGS - Sting
  createBaseElement('Vigilant readiness', 'emotions', 105, 'Alert to danger, prepared for darkness.'),
  createBaseElement('Glowing blade warning', 'story-particles', 105, 'Light that reveals hidden threats.'),
  createBaseElement('Protective vigilance', 'characteristics', 105, 'Always watching, always ready to defend.'),
  createBaseElement('Legendary weapon', 'tropes', 105, 'The blade with its own story and power.'),
  createBaseElement('Blue-white glow', 'sensory', 105, 'Light cutting through darkness, warning of evil.'),
  createBaseElement('Drawing steel', 'momentum', 105, 'The moment of readying for battle.'),
  createBaseElement('Light conquers darkness', 'theme', 105, 'Small lights can pierce great shadows.'),
  createBaseElement('Weapon and wielder', 'relationship', 105, 'Tool that becomes extension of self.'),
  createBaseElement('Unsheathing for battle', 'beat', 105, 'The moment steel clears leather.'),

  // THE LORD OF THE RINGS - Council of Elrond
  createBaseElement('Solemn gathering weight', 'emotions', 106, 'Gravity of great minds deciding fate.'),
  createBaseElement('War council assembly', 'story-particles', 106, 'Leaders gathering to face impossible odds.'),
  createBaseElement('Collective wisdom', 'characteristics', 106, 'Many minds working toward one solution.'),
  createBaseElement('Council of heroes', 'tropes', 106, 'The meeting where the fellowship forms.'),
  createBaseElement('Ancient hall echoes', 'sensory', 106, 'Voices bouncing off stone, history listening.'),
  createBaseElement('Pledging to the cause', 'momentum', 106, 'The moment of committing to impossible odds.'),
  createBaseElement('Unity against darkness', 'theme', 106, 'Disparate forces joining one purpose.'),
  createBaseElement('Fellowship forming', 'relationship', 106, 'Strangers becoming brothers in arms.'),
  createBaseElement('Assembling the team', 'beat', 106, 'When the heroes first come together.'),

  // THE LORD OF THE RINGS - Destruction of the Ring
  createBaseElement('Triumphant release', 'emotions', 107, 'Burden finally, impossibly lifted.'),
  createBaseElement('Final sacrifice moment', 'story-particles', 107, 'Everything comes down to one choice.'),
  createBaseElement('Ultimate resolve', 'characteristics', 107, 'Strength to do what must be done.'),
  createBaseElement('Eucatastrophe', 'tropes', 107, 'Sudden joyous turn from certain doom.'),
  createBaseElement('Ring melting in fire', 'sensory', 107, 'Gold dissolving, evil screaming, world shifting.'),
  createBaseElement('Letting go forever', 'momentum', 107, 'Release that changes everything.'),
  createBaseElement('Evil self-destructs', 'theme', 107, 'Darkness contains seeds of own destruction.'),
  createBaseElement('Savior and destroyer', 'relationship', 107, 'Saving the world by destroying your burden.'),
  createBaseElement('Completing the mission', 'beat', 107, 'The final triumphant act.'),

  // THE LORD OF THE RINGS - Fellowship formation
  createBaseElement('Inspiring solidarity', 'emotions', 108, 'Separate hearts beating as one.'),
  createBaseElement('Oath of brotherhood', 'story-particles', 108, 'Promises made that bind souls.'),
  createBaseElement('United diversity', 'characteristics', 108, 'Different strengths becoming one force.'),
  createBaseElement('The fellowship assembles', 'tropes', 108, 'Unlikely heroes joining forces.'),
  createBaseElement('Clasped hands in circle', 'sensory', 108, 'Physical touch sealing spiritual bond.'),
  createBaseElement('Joining the quest', 'momentum', 108, 'Committing alongside others to shared fate.'),
  createBaseElement('Strength in unity', 'theme', 108, 'Together we are more than sum of parts.'),
  createBaseElement('Brothers in arms', 'relationship', 108, 'Combat forging unbreakable bonds.'),
  createBaseElement('The vow together', 'beat', 108, 'Pledging as one to face darkness.'),

  // THE LORD OF THE RINGS - Mount Doom eruption
  createBaseElement('Apocalyptic awe', 'emotions', 109, 'Terror and wonder at world ending.'),
  createBaseElement('Volcano exploding', 'story-particles', 109, 'Mountain consuming itself in fire.'),
  createBaseElement('Cataclysmic force', 'characteristics', 109, 'Power that reshapes landscapes.'),
  createBaseElement('World-changing event', 'tropes', 109, 'The moment that rewrites everything.'),
  createBaseElement('Ash raining down', 'sensory', 109, 'Sky dark with falling destruction.'),
  createBaseElement('Erupting into chaos', 'momentum', 109, 'Explosion that changes the world.'),
  createBaseElement('Price of victory', 'theme', 109, 'Winning requires destroying much.'),
  createBaseElement('Witnesses to ending', 'relationship', 109, 'Sharing the moment everything changes.'),
  createBaseElement('The world breaks', 'beat', 109, 'When geography itself transforms.'),

  // DUNE - Paul Atreides
  createBaseElement('Prescient dread', 'emotions', 110, 'Knowing the terrible future you must create.'),
  createBaseElement('Messiah reluctance', 'story-particles', 110, 'Chosen one who fears his own destiny.'),
  createBaseElement('Forced maturity', 'characteristics', 110, 'Childhood stolen by necessity.'),
  createBaseElement('Chosen one burden', 'tropes', 110, 'Destiny selected you, not the other way.'),
  createBaseElement('Spice-blue eyes', 'sensory', 110, 'Irises stained by consuming the sacred.'),
  createBaseElement('Becoming the prophet', 'momentum', 110, 'Stepping into the role you dreaded.'),
  createBaseElement('Predetermined fate', 'theme', 110, 'Can you escape what you\'re meant to be.'),
  createBaseElement('Son and mother conspiracy', 'relationship', 110, 'Partnered in schemes across generations.'),
  createBaseElement('Taking the throne', 'beat', 110, 'Seizing power you never wanted.'),

  // DUNE - Baron Harkonnen
  createBaseElement('Bloated malice', 'emotions', 111, 'Corruption given flesh and appetite.'),
  createBaseElement('Scheming villain', 'story-particles', 111, 'Plans within plans within plans.'),
  createBaseElement('Grotesque cruelty', 'characteristics', 111, 'Evil that revels in causing pain.'),
  createBaseElement('Decadent tyrant', 'tropes', 111, 'Absolute power wielded with gleeful sadism.'),
  createBaseElement('Suspensor-float hiss', 'sensory', 111, 'Mechanical breathing of unnatural movement.'),
  createBaseElement('Plotting and scheming', 'momentum', 111, 'Weaving webs of manipulation.'),
  createBaseElement('Unchecked greed', 'theme', 111, 'Want without limit, hunger without end.'),
  createBaseElement('Abuser and victim', 'relationship', 111, 'Power wielded to break and dominate.'),
  createBaseElement('Revealing the conspiracy', 'beat', 111, 'When the plot comes to light.'),

  // DUNE - Arrakis desert
  createBaseElement('Thirst-driven fear', 'emotions', 112, 'Water as the most precious thing.'),
  createBaseElement('Endless dunes', 'story-particles', 112, 'Sand stretching to every horizon.'),
  createBaseElement('Harsh unforgiving', 'characteristics', 112, 'Environment that kills the unprepared.'),
  createBaseElement('Desert planet', 'tropes', 112, 'World of sand and survival.'),
  createBaseElement('Burning sun glare', 'sensory', 112, 'Heat that ripples air and scorches skin.'),
  createBaseElement('Trudging through sand', 'momentum', 112, 'Every step sinking, progress exhausting.'),
  createBaseElement('Nature as crucible', 'theme', 112, 'Harsh lands forging harder people.'),
  createBaseElement('Desert and dweller', 'relationship', 112, 'Place that shapes those who survive it.'),
  createBaseElement('First sandstorm', 'beat', 112, 'When the desert shows its power.'),

  // DUNE - Sietch Tabr
  createBaseElement('Safe refuge relief', 'emotions', 113, 'Shelter from the killing world outside.'),
  createBaseElement('Hidden sanctuary', 'story-particles', 113, 'Secret place of survival and culture.'),
  createBaseElement('Communal survival', 'characteristics', 113, 'Together we endure what alone kills.'),
  createBaseElement('Desert stronghold', 'tropes', 113, 'Fortress carved from rock and necessity.'),
  createBaseElement('Still-suit recycled breath', 'sensory', 113, 'Tasting your own moisture reclaimed.'),
  createBaseElement('Seeking shelter', 'momentum', 113, 'Finding safety in hostile lands.'),
  createBaseElement('Community sustains', 'theme', 113, 'Survival through shared struggle.'),
  createBaseElement('Outsider becoming tribe', 'relationship', 113, 'Stranger adopted into closed society.'),
  createBaseElement('Entering the sietch', 'beat', 113, 'First glimpse of hidden world.'),

  // DUNE - Crysknife
  createBaseElement('Sacred respect', 'emotions', 114, 'Reverence for tool made from life.'),
  createBaseElement('Tooth made blade', 'story-particles', 114, 'Weapon crafted from defeated creature.'),
  createBaseElement('Ritual significance', 'characteristics', 114, 'Object heavy with cultural meaning.'),
  createBaseElement('Sacred weapon', 'tropes', 114, 'Blade that carries spiritual weight.'),
  createBaseElement('Bone-smooth grip', 'sensory', 114, 'Warmth of once-living tooth.'),
  createBaseElement('Claiming the sacred', 'momentum', 114, 'Earning right to wield holy tool.'),
  createBaseElement('Tradition binds', 'theme', 114, 'Culture encoded in objects.'),
  createBaseElement('Wielder and weapon ritual', 'relationship', 114, 'Bond sealed by ceremony and blood.'),
  createBaseElement('Receiving the blade', 'beat', 114, 'Moment of being entrusted with sacred.'),

  // DUNE - Spice
  createBaseElement('Euphoric dependence', 'emotions', 115, 'Pleasure that becomes necessity.'),
  createBaseElement('Precious resource', 'story-particles', 115, 'Substance wars are fought over.'),
  createBaseElement('Consciousness-expanding', 'characteristics', 115, 'Opening mind to impossible visions.'),
  createBaseElement('Magical resource', 'tropes', 115, 'What everyone wants, what drives the world.'),
  createBaseElement('Cinnamon sharp scent', 'sensory', 115, 'Smell that permeates everything.'),
  createBaseElement('Ascending to prescience', 'momentum', 115, 'Rising into forbidden knowledge.'),
  createBaseElement('Addiction to power', 'theme', 115, 'How need for substance drives empires.'),
  createBaseElement('Spice and prescient', 'relationship', 115, 'Substance and user becoming one.'),
  createBaseElement('First spice vision', 'beat', 115, 'When future floods the mind.'),

  // DUNE - Water of Life ceremony
  createBaseElement('Transcendent terror', 'emotions', 116, 'Fear and ecstasy of transformation.'),
  createBaseElement('Ritual transformation', 'story-particles', 116, 'Ceremony that fundamentally changes you.'),
  createBaseElement('Breaking boundaries', 'characteristics', 116, 'Crossing into forbidden territory.'),
  createBaseElement('Initiation rite', 'tropes', 116, 'Trial that makes you something new.'),
  createBaseElement('Bitter poison taste', 'sensory', 116, 'Liquid death becoming enlightenment.'),
  createBaseElement('Crossing the threshold', 'momentum', 116, 'Point of no return into transformation.'),
  createBaseElement('Rebirth through death', 'theme', 116, 'Dying to what you were.'),
  createBaseElement('Initiate and witness', 'relationship', 116, 'Those who watch you transform.'),
  createBaseElement('Drinking the poison', 'beat', 116, 'Swallowing what should kill you.'),

  // DUNE - Sandworm riding
  createBaseElement('Exhilarating conquest', 'emotions', 117, 'Mastering the untameable.'),
  createBaseElement('Riding the beast', 'story-particles', 117, 'Taming forces beyond human.'),
  createBaseElement('Fearless mastery', 'characteristics', 117, 'Control through courage and skill.'),
  createBaseElement('Beast master', 'tropes', 117, 'Human commanding nature\'s fury.'),
  createBaseElement('Thunder of sand', 'sensory', 117, 'Ground shaking with leviathan movement.'),
  createBaseElement('Mounting the worm', 'momentum', 117, 'Leaping onto impossible ride.'),
  createBaseElement('Mastering nature', 'theme', 117, 'Humans dominating their environment.'),
  createBaseElement('Rider and beast', 'relationship', 117, 'Temporary dominion over wild.'),
  createBaseElement('First successful ride', 'beat', 117, 'Proving yourself through impossible feat.'),

  // DUNE - Fall of House Atreides
  createBaseElement('Devastating betrayal', 'emotions', 118, 'Everything you built destroyed by trust broken.'),
  createBaseElement('Dynasty collapsing', 'story-particles', 118, 'Great house brought to ruin.'),
  createBaseElement('Noble tragedy', 'characteristics', 118, 'Virtue unable to stop downfall.'),
  createBaseElement('Fall from grace', 'tropes', 118, 'Mighty brought low by schemes.'),
  createBaseElement('Smoke and screaming', 'sensory', 118, 'Home becoming battlefield and tomb.'),
  createBaseElement('Fleeing the massacre', 'momentum', 118, 'Escape from total destruction.'),
  createBaseElement('Betrayal destroys', 'theme', 118, 'Trust weaponized brings ruin.'),
  createBaseElement('Dynasty and heir', 'relationship', 118, 'Surviving to avenge fallen house.'),
  createBaseElement('The attack begins', 'beat', 118, 'Night the world ends.'),

  // DUNE - Paul's ascension
  createBaseElement('Reluctant apotheosis', 'emotions', 119, 'Becoming god you never wanted to be.'),
  createBaseElement('Prophesied rise', 'story-particles', 119, 'Destiny finally fulfilled.'),
  createBaseElement('Transcendent power', 'characteristics', 119, 'Beyond human limitations.'),
  createBaseElement('Messiah revealed', 'tropes', 119, 'The chosen one claiming their role.'),
  createBaseElement('Multitude roaring worship', 'sensory', 119, 'Thousands proclaiming your divinity.'),
  createBaseElement('Seizing control', 'momentum', 119, 'Taking power destiny promised.'),
  createBaseElement('Cost of greatness', 'theme', 119, 'Price paid for transcendence.'),
  createBaseElement('Emperor and empire', 'relationship', 119, 'Ruler shaping civilization.'),
  createBaseElement('Claiming the throne', 'beat', 119, 'Moment of absolute victory.'),

  // AND THEN THERE WERE NONE - Vera Claythorne
  createBaseElement('Mounting paranoia', 'emotions', 120, 'Trust eroding into terror.'),
  createBaseElement('Guilty conscience', 'story-particles', 120, 'Past sins haunting present.'),
  createBaseElement('Calculated survival', 'characteristics', 120, 'Doing anything to stay alive.'),
  createBaseElement('Final girl', 'tropes', 120, 'Last one standing through cunning.'),
  createBaseElement('Noose swaying overhead', 'sensory', 120, 'Death waiting in peripheral vision.'),
  createBaseElement('Suspecting everyone', 'momentum', 120, 'Trust becoming liability.'),
  createBaseElement('Justice inescapable', 'theme', 120, 'Past crimes demand payment.'),
  createBaseElement('Survivor and victims', 'relationship', 120, 'Outlasting others through guilt.'),
  createBaseElement('Facing accusation', 'beat', 120, 'When your secret becomes known.'),

  // AND THEN THERE WERE NONE - Judge Wargrave
  createBaseElement('Cold satisfaction', 'emotions', 121, 'Pleasure in orchestrated punishment.'),
  createBaseElement('Puppet master', 'story-particles', 121, 'Controller of all fates.'),
  createBaseElement('Methodical judgment', 'characteristics', 121, 'Precision in dispensing justice.'),
  createBaseElement('Hidden mastermind', 'tropes', 121, 'True villain revealed at the end.'),
  createBaseElement('Gavel striking wood', 'sensory', 121, 'Sound of final judgment.'),
  createBaseElement('Judging and sentencing', 'momentum', 121, 'Playing god with lives.'),
  createBaseElement('Vigilante justice', 'theme', 121, 'Law taken into own hands.'),
  createBaseElement('Judge and condemned', 'relationship', 121, 'Power to decide life and death.'),
  createBaseElement('Revealing the mastermind', 'beat', 121, 'Truth of who orchestrated all.'),

  // AND THEN THERE WERE NONE - Soldier Island
  createBaseElement('Claustrophobic isolation', 'emotions', 122, 'Trapped with danger, no escape.'),
  createBaseElement('Cut-off location', 'story-particles', 122, 'Island prison with no way out.'),
  createBaseElement('Sinister atmosphere', 'characteristics', 122, 'Place heavy with dread.'),
  createBaseElement('Isolated mansion', 'tropes', 122, 'Trapped location with no escape.'),
  createBaseElement('Storm-lashed shores', 'sensory', 122, 'Waves cutting off salvation.'),
  createBaseElement('Trapped together', 'momentum', 122, 'Forced proximity with killers.'),
  createBaseElement('Nowhere to run', 'theme', 122, 'Isolation breeds paranoia.'),
  createBaseElement('Trapped strangers', 'relationship', 122, 'Forced cohabitation with murderers.'),
  createBaseElement('Storm cuts them off', 'beat', 122, 'Realizing there\'s no escape.'),

  // AND THEN THERE WERE NONE - The dining room
  createBaseElement('Gathering dread', 'emotions', 123, 'Forced meals with would-be killers.'),
  createBaseElement('Dinner party horror', 'story-particles', 123, 'Civilized veneer over violence.'),
  createBaseElement('Tense civility', 'characteristics', 123, 'Politeness masking terror.'),
  createBaseElement('Last supper', 'tropes', 123, 'Meal before everything changes.'),
  createBaseElement('Clinking silverware', 'sensory', 123, 'Normal sounds made sinister.'),
  createBaseElement('Gathering for judgment', 'momentum', 123, 'Coming together to face accusations.'),
  createBaseElement('Guilt revealed', 'theme', 123, 'Secrets exposed over dinner.'),
  createBaseElement('Accusers dining together', 'relationship', 123, 'Forced intimacy of suspects.'),
  createBaseElement('Figurine disappears', 'beat', 123, 'Another death, another missing piece.'),

  // AND THEN THERE WERE NONE - Nursery rhyme poem
  createBaseElement('Childish menace', 'emotions', 124, 'Innocent words made terrifying.'),
  createBaseElement('Counting down deaths', 'story-particles', 124, 'Prophecy of systematic murder.'),
  createBaseElement('Methodical pattern', 'characteristics', 124, 'Order to the killing.'),
  createBaseElement('Death omen', 'tropes', 124, 'Object predicting doom.'),
  createBaseElement('Sing-song cadence', 'sensory', 124, 'Childish rhythm of death.'),
  createBaseElement('Following the pattern', 'momentum', 124, 'Deaths matching prophecy.'),
  createBaseElement('Fate predetermined', 'theme', 124, 'Cannot escape written destiny.'),
  createBaseElement('Victims and prophecy', 'relationship', 124, 'Lives controlled by poem.'),
  createBaseElement('Pattern recognized', 'beat', 124, 'Realizing the method.'),

  // AND THEN THERE WERE NONE - Indian figurines
  createBaseElement('Countdown anxiety', 'emotions', 125, 'Watching death approach one by one.'),
  createBaseElement('Disappearing markers', 'story-particles', 125, 'Visual tally of the dead.'),
  createBaseElement('Ominous symbolism', 'characteristics', 125, 'Objects predicting doom.'),
  createBaseElement('Death tokens', 'tropes', 125, 'Physical manifestation of fate.'),
  createBaseElement('Ceramic cold touch', 'sensory', 125, 'Lifeless objects marking lives.'),
  createBaseElement('Counting down', 'momentum', 125, 'Approaching inevitable zero.'),
  createBaseElement('Time runs out', 'theme', 125, 'Finite chances at survival.'),
  createBaseElement('Survivors and dead', 'relationship', 125, 'Living counting the lost.'),
  createBaseElement('Another one falls', 'beat', 125, 'Death reducing the count.'),

  // AND THEN THERE WERE NONE - First murder
  createBaseElement('Shocking violation', 'emotions', 126, 'Innocence shattered by violence.'),
  createBaseElement('Breaking the peace', 'story-particles', 126, 'First blood changes everything.'),
  createBaseElement('Sudden violence', 'characteristics', 126, 'Calm shattered by death.'),
  createBaseElement('Inciting incident', 'tropes', 126, 'Event that starts the nightmare.'),
  createBaseElement('Choking gasps', 'sensory', 126, 'Sounds of life leaving.'),
  createBaseElement('Crossing into chaos', 'momentum', 126, 'Moment order becomes murder.'),
  createBaseElement('Innocence lost', 'theme', 126, 'Safety revealed as illusion.'),
  createBaseElement('Witnesses to horror', 'relationship', 126, 'Seeing death together.'),
  createBaseElement('First blood', 'beat', 126, 'When someone dies first.'),

  // AND THEN THERE WERE NONE - Final revelation
  createBaseElement('Stunned comprehension', 'emotions', 127, 'Pieces falling into horrible place.'),
  createBaseElement('Truth unveiled', 'story-particles', 127, 'Mystery solved too late.'),
  createBaseElement('Posthumous confession', 'characteristics', 127, 'Dead man\'s final words.'),
  createBaseElement('Message from beyond', 'tropes', 127, 'Killer\'s last revelation.'),
  createBaseElement('Paper crinkling', 'sensory', 127, 'Letter revealing everything.'),
  createBaseElement('Understanding at last', 'momentum', 127, 'Clarity coming too late.'),
  createBaseElement('Truth too late', 'theme', 127, 'Knowledge that can\'t save you.'),
  createBaseElement('Dead judge and readers', 'relationship', 127, 'Posthumous confession to world.'),
  createBaseElement('Reading the letter', 'beat', 127, 'Final truth revealed.'),

  // AND THEN THERE WERE NONE - Storm isolation
  createBaseElement('Weather-trapped dread', 'emotions', 128, 'Nature conspiring to trap you.'),
  createBaseElement('Boat can\'t come', 'story-particles', 128, 'Rescue delayed by elements.'),
  createBaseElement('Natural prison', 'characteristics', 128, 'Weather as warden.'),
  createBaseElement('Stranded scenario', 'tropes', 128, 'Cut off by forces beyond control.'),
  createBaseElement('Wind howling fury', 'sensory', 128, 'Storm celebrating your doom.'),
  createBaseElement('Watching storm rage', 'momentum', 128, 'Waiting for weather to free you.'),
  createBaseElement('Trapped by fate', 'theme', 128, 'Circumstances conspiring against escape.'),
  createBaseElement('Prisoners of weather', 'relationship', 128, 'Shared captivity by nature.'),
  createBaseElement('Hope of rescue fades', 'beat', 128, 'Realizing help won\'t come.'),

  // AND THEN THERE WERE NONE - Mass poisoning
  createBaseElement('Betrayed hospitality', 'emotions', 129, 'Food and drink made weapons.'),
  createBaseElement('Communal death', 'story-particles', 129, 'Shared meal becoming shared doom.'),
  createBaseElement('Invisible murder', 'characteristics', 129, 'Death in the drinks you share.'),
  createBaseElement('Poisoned feast', 'tropes', 129, 'Hospitality hiding murder.'),
  createBaseElement('Bitter almond smell', 'sensory', 129, 'Scent of poison in the glass.'),
  createBaseElement('Consuming death', 'momentum', 129, 'Swallowing your own doom.'),
  createBaseElement('Trust as weapon', 'theme', 129, 'Betrayal through basic needs.'),
  createBaseElement('Host and poisoned guests', 'relationship', 129, 'Provider as killer.'),
  createBaseElement('Everyone drinking together', 'beat', 129, 'Shared doom in shared cups.'),

  // THE SHINING - Jack Torrance
  createBaseElement('Spiraling madness', 'emotions', 130, 'Sanity unraveling thread by thread.'),
  createBaseElement('Father\'s descent', 'story-particles', 130, 'Patriarch becoming monster.'),
  createBaseElement('Volatile temper', 'characteristics', 130, 'Violence always bubbling beneath.'),
  createBaseElement('Descent into madness', 'tropes', 130, 'Good man corrupted completely.'),
  createBaseElement('Whiskey breath', 'sensory', 130, 'Alcohol and anger on his breath.'),
  createBaseElement('Succumbing to hotel', 'momentum', 130, 'Giving in to dark influence.'),
  createBaseElement('Addiction destroys family', 'theme', 130, 'How weakness tears apart loved ones.'),
  createBaseElement('Father and family terrorizer', 'relationship', 130, 'Protector becoming predator.'),
  createBaseElement('Breaking through the door', 'beat', 130, 'When father becomes hunter.'),

  // THE SHINING - Danny
  createBaseElement('Psychic terror', 'emotions', 131, 'Seeing horrors others can\'t.'),
  createBaseElement('Child\'s second sight', 'story-particles', 131, 'Gift that shows too much.'),
  createBaseElement('Frightened clairvoyance', 'characteristics', 131, 'Knowing what\'s coming, unable to stop it.'),
  createBaseElement('Psychic child', 'tropes', 131, 'Kid who sees what adults can\'t.'),
  createBaseElement('Tony\'s croaking voice', 'sensory', 131, 'Imaginary friend warning.'),
  createBaseElement('Fleeing father', 'momentum', 131, 'Running from who should protect you.'),
  createBaseElement('Innocence sees truth', 'theme', 131, 'Children perceiving adult darkness.'),
  createBaseElement('Son and possessed father', 'relationship', 131, 'Child fearing parent.'),
  createBaseElement('Hiding in the bathroom', 'beat', 131, 'Seeking shelter from father.'),

  // THE SHINING - Overlook Hotel
  createBaseElement('Malevolent presence', 'emotions', 132, 'Building that hates and hungers.'),
  createBaseElement('Haunted edifice', 'story-particles', 132, 'Structure with evil memory.'),
  createBaseElement('Corrupting influence', 'characteristics', 132, 'Place that poisons minds.'),
  createBaseElement('Evil location', 'tropes', 132, 'Building as antagonist.'),
  createBaseElement('Empty halls echo', 'sensory', 132, 'Vastness amplifying solitude.'),
  createBaseElement('Trapped in isolation', 'momentum', 132, 'Snowbound with evil.'),
  createBaseElement('Places remember evil', 'theme', 132, 'Locations absorbing darkness.'),
  createBaseElement('Building and inhabitants', 'relationship', 132, 'Structure feeding on residents.'),
  createBaseElement('First ghostly encounter', 'beat', 132, 'Realizing hotel is alive.'),

  // THE SHINING - Room 237
  createBaseElement('Horrified revulsion', 'emotions', 133, 'Desire turning to disgust.'),
  createBaseElement('Forbidden chamber', 'story-particles', 133, 'Room that should stay locked.'),
  createBaseElement('Corrupted sanctuary', 'characteristics', 133, 'Beauty rotting into horror.'),
  createBaseElement('Forbidden room', 'tropes', 133, 'The one door you shouldn\'t open.'),
  createBaseElement('Decay beneath perfume', 'sensory', 133, 'Beauty masking rot.'),
  createBaseElement('Entering the forbidden', 'momentum', 133, 'Opening door better left closed.'),
  createBaseElement('Desire corrupts', 'theme', 133, 'Want leading to horror.'),
  createBaseElement('Victim and temptation', 'relationship', 133, 'Lured by false beauty.'),
  createBaseElement('Beauty becomes horror', 'beat', 133, 'Attractive revealing hideous truth.'),

  // THE SHINING - Typewriter
  createBaseElement('Creative frustration', 'emotions', 134, 'Art blocked by madness.'),
  createBaseElement('Writer\'s obsession', 'story-particles', 134, 'Work consuming creator.'),
  createBaseElement('Manic repetition', 'characteristics', 134, 'Same words over and over.'),
  createBaseElement('Madman\'s manuscript', 'tropes', 134, 'Work revealing insanity.'),
  createBaseElement('Keys clacking endless', 'sensory', 134, 'Mechanical rhythm of obsession.'),
  createBaseElement('Typing into madness', 'momentum', 134, 'Work becoming symptom.'),
  createBaseElement('Art reflects madness', 'theme', 134, 'Creation showing creator\'s state.'),
  createBaseElement('Writer and terrible work', 'relationship', 134, 'Madness made manifest.'),
  createBaseElement('Reading the manuscript', 'beat', 134, 'Discovering extent of madness.'),

  // THE SHINING - Hedge maze
  createBaseElement('Hunted panic', 'emotions', 135, 'Prey fleeing predator in labyrinth.'),
  createBaseElement('Twisting paths', 'story-particles', 135, 'Every turn might be wrong.'),
  createBaseElement('Disorienting pursuit', 'characteristics', 135, 'Lost while being chased.'),
  createBaseElement('Maze chase', 'tropes', 135, 'Final confrontation in confusing space.'),
  createBaseElement('Snow-muffled footsteps', 'sensory', 135, 'Hunter approaching in silence.'),
  createBaseElement('Running the maze', 'momentum', 135, 'Fleeing through confusion.'),
  createBaseElement('Hunter becomes hunted', 'theme', 135, 'Predator trapped by own pursuit.'),
  createBaseElement('Father hunting son', 'relationship', 135, 'Parent as predator.'),
  createBaseElement('Chase through snow', 'beat', 135, 'Final pursuit begins.'),

  // THE SHINING - "Here's Johnny!"
  createBaseElement('Door-breaking terror', 'emotions', 136, 'Barrier destroyed, death enters.'),
  createBaseElement('Iconic horror moment', 'story-particles', 136, 'Line that becomes legend.'),
  createBaseElement('Homicidal mania', 'characteristics', 136, 'Violence with grinning face.'),
  createBaseElement('Iconic horror line', 'tropes', 136, 'Moment that defines genre.'),
  createBaseElement('Splintering wood', 'sensory', 136, 'Axe breaking through safety.'),
  createBaseElement('Bursting through', 'momentum', 136, 'Violence shattering barrier.'),
  createBaseElement('Safety is illusion', 'theme', 136, 'No door can keep evil out.'),
  createBaseElement('Killer and victim separated by door', 'relationship', 136, 'Thin wood between life and death.'),
  createBaseElement('Breaking through the barrier', 'beat', 136, 'When safety shatters.'),

  // THE SHINING - Bathroom revelation
  createBaseElement('Dawning horror', 'emotions', 137, 'Understanding the terrible truth.'),
  createBaseElement('Reading the madness', 'story-particles', 137, 'Pages revealing extent of fall.'),
  createBaseElement('Truth in repetition', 'characteristics', 137, 'Same words showing broken mind.'),
  createBaseElement('All work no play', 'tropes', 137, 'Repeated phrase revealing insanity.'),
  createBaseElement('Paper rustling pages', 'sensory', 137, 'Turning through identical madness.'),
  createBaseElement('Discovering the truth', 'momentum', 137, 'Realization of how far gone.'),
  createBaseElement('Madness revealed', 'theme', 137, 'Work showing broken creator.'),
  createBaseElement('Wife and mad husband', 'relationship', 137, 'Realizing spouse is gone.'),
  createBaseElement('Seeing the manuscript', 'beat', 137, 'Truth of madness in pages.'),

  // THE SHINING - Winter storm
  createBaseElement('Weather-trapped isolation', 'emotions', 138, 'Nature sealing you in with evil.'),
  createBaseElement('Snowbound prison', 'story-particles', 138, 'Winter making escape impossible.'),
  createBaseElement('Natural barrier', 'characteristics', 138, 'Elements conspiring to trap.'),
  createBaseElement('Snowed in', 'tropes', 138, 'Weather cutting off escape.'),
  createBaseElement('Blizzard howling', 'sensory', 138, 'Wind burying the world.'),
  createBaseElement('Trapped by snow', 'momentum', 138, 'Storm preventing escape.'),
  createBaseElement('Isolation breeds madness', 'theme', 138, 'Cut off from world, losing mind.'),
  createBaseElement('Family snowbound together', 'relationship', 138, 'Trapped with turning danger.'),
  createBaseElement('First snow falls', 'beat', 138, 'Prison walls rising in white.'),

  // THE SHINING - Hotel possession
  createBaseElement('Identity dissolving', 'emotions', 139, 'Self replaced by other.'),
  createBaseElement('Building claiming soul', 'story-particles', 139, 'Place consuming person.'),
  createBaseElement('Puppet of evil', 'characteristics', 139, 'Will replaced by malice.'),
  createBaseElement('Demonic possession', 'tropes', 139, 'Evil taking over good.'),
  createBaseElement('Ghosts whispering', 'sensory', 139, 'Dead voices in living ears.'),
  createBaseElement('Surrendering to darkness', 'momentum', 139, 'Giving in to evil influence.'),
  createBaseElement('Evil corrupts the weak', 'theme', 139, 'Darkness claiming flawed souls.'),
  createBaseElement('Building and vessel', 'relationship', 139, 'Place using person as tool.'),
  createBaseElement('Accepting the offer', 'beat', 139, 'Moment of yielding to evil.'),

  // ALL THE LIGHT WE CANNOT SEE - Marie-Laure
  createBaseElement('Brave despite blindness', 'emotions', 140, 'Courage in unseeing dark.'),
  createBaseElement('Blind girl\'s journey', 'story-particles', 140, 'Navigating war without sight.'),
  createBaseElement('Perceptive vulnerability', 'characteristics', 140, 'Seeing truth through darkness.'),
  createBaseElement('Blind protagonist', 'tropes', 140, 'Sightless seeing what others miss.'),
  createBaseElement('Fingers reading braille', 'sensory', 140, 'Touch as vision.'),
  createBaseElement('Feeling her way forward', 'momentum', 140, 'Navigating blind through danger.'),
  createBaseElement('Inner light conquers', 'theme', 140, 'Spirit overcoming darkness.'),
  createBaseElement('Girl and guiding father', 'relationship', 140, 'Trust in parent\'s voice.'),
  createBaseElement('Learning the miniature', 'beat', 140, 'Memorizing city by touch.'),

  // ALL THE LIGHT WE CANNOT SEE - Werner
  createBaseElement('Complicit guilt', 'emotions', 141, 'Serving evil you recognize.'),
  createBaseElement('Talented youth conscripted', 'story-particles', 141, 'Gift making you weapon.'),
  createBaseElement('Conflicted duty', 'characteristics', 141, 'Following orders against conscience.'),
  createBaseElement('Good soldier bad war', 'tropes', 141, 'Decent person in terrible cause.'),
  createBaseElement('Radio static searching', 'sensory', 141, 'Listening for enemies, hearing souls.'),
  createBaseElement('Following orders reluctantly', 'momentum', 141, 'Obeying despite knowing wrong.'),
  createBaseElement('Complicity in evil', 'theme', 141, 'Serving darkness from inside.'),
  createBaseElement('Soldier and civilians', 'relationship', 141, 'Weapon aimed at innocent.'),
  createBaseElement('Joining the army', 'beat', 141, 'Enlisting in wrong side.'),

  // ALL THE LIGHT WE CANNOT SEE - Saint-Malo
  createBaseElement('Walled city pride', 'emotions', 142, 'Beauty under siege.'),
  createBaseElement('Fortified coastal town', 'story-particles', 142, 'Ancient walls holding back war.'),
  createBaseElement('Historical grandeur', 'characteristics', 142, 'Past glory facing destruction.'),
  createBaseElement('Besieged city', 'tropes', 142, 'Beautiful place about to burn.'),
  createBaseElement('Salt spray on stone', 'sensory', 142, 'Sea meeting fortress walls.'),
  createBaseElement('Under siege', 'momentum', 142, 'Waiting for inevitable assault.'),
  createBaseElement('Beauty destroyed by war', 'theme', 142, 'History erased by violence.'),
  createBaseElement('City and residents', 'relationship', 142, 'Place shaping those who shelter there.'),
  createBaseElement('Bombs falling', 'beat', 142, 'Assault beginning.'),

  // ALL THE LIGHT WE CANNOT SEE - The radio room
  createBaseElement('Secret resistance', 'emotions', 143, 'Quiet defiance in hidden space.'),
  createBaseElement('Hidden broadcasting chamber', 'story-particles', 143, 'Sanctuary of forbidden communication.'),
  createBaseElement('Clandestine operations', 'characteristics', 143, 'Resistance from concealed room.'),
  createBaseElement('Secret headquarters', 'tropes', 143, 'Hidden base of resistance.'),
  createBaseElement('Tubes warming up', 'sensory', 143, 'Radio glowing to life.'),
  createBaseElement('Broadcasting resistance', 'momentum', 143, 'Speaking truth to power.'),
  createBaseElement('Small acts of defiance', 'theme', 143, 'Whispers against tyranny.'),
  createBaseElement('Broadcaster and listeners', 'relationship', 143, 'Voice reaching desperate ears.'),
  createBaseElement('First broadcast', 'beat', 143, 'Speaking forbidden truth.'),

  // ALL THE LIGHT WE CANNOT SEE - Model of Saint-Malo
  createBaseElement('Tactile memory', 'emotions', 144, 'Touching to remember and navigate.'),
  createBaseElement('Miniature city guide', 'story-particles', 144, 'Small version teaching large truth.'),
  createBaseElement('Patient craftsmanship', 'characteristics', 144, 'Detail made from love.'),
  createBaseElement('Map of home', 'tropes', 144, 'Object encoding belonging.'),
  createBaseElement('Smooth wood streets', 'sensory', 144, 'Fingertips learning paths.'),
  createBaseElement('Memorizing through touch', 'momentum', 144, 'Learning world through hands.'),
  createBaseElement('Love as preparation', 'theme', 144, 'Gift enabling survival.'),
  createBaseElement('Father and daughter gift', 'relationship', 144, 'Protection given through craft.'),
  createBaseElement('Presenting the model', 'beat', 144, 'Unveiling the gift.'),

  // ALL THE LIGHT WE CANNOT SEE - Radio transmitter
  createBaseElement('Technological hope', 'emotions', 145, 'Machine connecting across darkness.'),
  createBaseElement('Resistance device', 'story-particles', 145, 'Tool of rebellion.'),
  createBaseElement('Forbidden communication', 'characteristics', 145, 'Speaking when silenced.'),
  createBaseElement('MacGuffin of connection', 'tropes', 145, 'Device everyone seeks.'),
  createBaseElement('Crackling transmission', 'sensory', 145, 'Voice through static.'),
  createBaseElement('Sending signals', 'momentum', 145, 'Broadcasting into darkness.'),
  createBaseElement('Communication as resistance', 'theme', 145, 'Words fighting tyranny.'),
  createBaseElement('Sender and receiver', 'relationship', 145, 'Connection across distance.'),
  createBaseElement('Signal connecting them', 'beat', 145, 'Voices finding each other.'),

  // ALL THE LIGHT WE CANNOT SEE - Bombing of Saint-Malo
  createBaseElement('Apocalyptic bombardment', 'emotions', 146, 'Sky raining death.'),
  createBaseElement('City ablaze', 'story-particles', 146, 'Ancient beauty burning.'),
  createBaseElement('Indiscriminate destruction', 'characteristics', 146, 'War consuming all.'),
  createBaseElement('Firebombing sequence', 'tropes', 146, 'City destroyed from above.'),
  createBaseElement('Explosions shaking walls', 'sensory', 146, 'Thunder of falling bombs.'),
  createBaseElement('Hiding from death', 'momentum', 146, 'Sheltering from sky falling.'),
  createBaseElement('War destroys innocence', 'theme', 146, 'Violence erasing beauty.'),
  createBaseElement('Huddled survivors', 'relationship', 146, 'Strangers sharing shelter.'),
  createBaseElement('First bomb hits', 'beat', 146, 'Assault from heaven begins.'),

  // ALL THE LIGHT WE CANNOT SEE - Final broadcast
  createBaseElement('Last defiant message', 'emotions', 147, 'Speaking truth as world ends.'),
  createBaseElement('Transmission to void', 'story-particles', 147, 'Message sent despite danger.'),
  createBaseElement('Desperate communication', 'characteristics', 147, 'Reaching out before silence.'),
  createBaseElement('Final transmission', 'tropes', 147, 'Last message before end.'),
  createBaseElement('Voice fading to static', 'sensory', 147, 'Words dissolving into noise.'),
  createBaseElement('Speaking into darkness', 'momentum', 147, 'Message sent despite odds.'),
  createBaseElement('Voice matters', 'theme', 147, 'Speaking truth even when unheard.'),
  createBaseElement('Broadcaster and listener', 'relationship', 147, 'Connection across impossible odds.'),
  createBaseElement('Hearing the voice', 'beat', 147, 'Message received against all odds.'),

  // ALL THE LIGHT WE CANNOT SEE - Nazi occupation
  createBaseElement('Oppressed resentment', 'emotions', 148, 'Hating those who rule you.'),
  createBaseElement('Foreign occupation', 'story-particles', 148, 'Invaders controlling your home.'),
  createBaseElement('Conquered populace', 'characteristics', 148, 'Proud people made subjects.'),
  createBaseElement('Occupation narrative', 'tropes', 148, 'Enemy controlling your land.'),
  createBaseElement('Jackboots on cobblestones', 'sensory', 148, 'Sound of marching conquerors.'),
  createBaseElement('Living under tyranny', 'momentum', 148, 'Enduring foreign rule.'),
  createBaseElement('Resistance in occupied land', 'theme', 148, 'Fighting back from shadows.'),
  createBaseElement('Occupiers and occupied', 'relationship', 148, 'Power over resentful subjects.'),
  createBaseElement('Troops marching in', 'beat', 148, 'Conquerors arriving.'),

  // ALL THE LIGHT WE CANNOT SEE - Liberation
  createBaseElement('Tearful jubilation', 'emotions', 149, 'Freedom after oppression.'),
  createBaseElement('Invaders driven out', 'story-particles', 149, 'Home reclaimed from enemy.'),
  createBaseElement('Joyous release', 'characteristics', 149, 'Weight lifted, chains broken.'),
  createBaseElement('Liberation sequence', 'tropes', 149, 'Freedom restored.'),
  createBaseElement('Church bells ringing', 'sensory', 149, 'Sound of celebration.'),
  createBaseElement('Reclaiming freedom', 'momentum', 149, 'Taking back what was stolen.'),
  createBaseElement('Freedom costs', 'theme', 149, 'Liberation paid for in blood.'),
  createBaseElement('Liberators and liberated', 'relationship', 149, 'Saviors restoring hope.'),
  createBaseElement('The day of freedom', 'beat', 149, 'Occupation ending.'),

  // GONE GIRL - Amy Dunne
  createBaseElement('Calculated malice', 'emotions', 150, 'Anger turned to perfect plan.'),
  createBaseElement('Vengeful mastermind', 'story-particles', 150, 'Revenge as elaborate art.'),
  createBaseElement('Methodical sociopathy', 'characteristics', 150, 'Manipulation without conscience.'),
  createBaseElement('Femme fatale', 'tropes', 150, 'Beautiful woman as deadly weapon.'),
  createBaseElement('Tight smile hiding rage', 'sensory', 150, 'Expression masking fury.'),
  createBaseElement('Executing the plan', 'momentum', 150, 'Each step of perfect revenge.'),
  createBaseElement('Revenge perfected', 'theme', 150, 'Payback as art form.'),
  createBaseElement('Wife weaponizing marriage', 'relationship', 150, 'Love twisted into weapon.'),
  createBaseElement('Disappearing', 'beat', 150, 'Vanishing to frame him.'),

  // GONE GIRL - Nick Dunne
  createBaseElement('Bewildered innocence', 'emotions', 151, 'Accused of what you didn\'t do.'),
  createBaseElement('Falsely accused husband', 'story-particles', 151, 'Innocent man framed perfectly.'),
  createBaseElement('Hapless victim', 'characteristics', 151, 'Caught in web you can\'t see.'),
  createBaseElement('Wrong man accused', 'tropes', 151, 'Innocent suspected of crime.'),
  createBaseElement('Interrogation room sweat', 'sensory', 151, 'Fear despite innocence.'),
  createBaseElement('Protesting innocence', 'momentum', 151, 'Defending against perfect frame.'),
  createBaseElement('Marriage as warfare', 'theme', 151, 'Love becoming battleground.'),
  createBaseElement('Husband accused by wife', 'relationship', 151, 'Partner becoming enemy.'),
  createBaseElement('Discovered as suspect', 'beat', 151, 'When all evidence points to you.'),

  // GONE GIRL - The bar
  createBaseElement('Nostalgic refuge', 'emotions', 152, 'Place of escape and comfort.'),
  createBaseElement('Failing business', 'story-particles', 152, 'Investment bleeding money.'),
  createBaseElement('Masculine retreat', 'characteristics', 152, 'Space away from complexity.'),
  createBaseElement('Hangout location', 'tropes', 152, 'Where protagonist goes to think.'),
  createBaseElement('Beer and wood polish', 'sensory', 152, 'Smells of familiar escape.'),
  createBaseElement('Hiding out', 'momentum', 152, 'Retreating from complications.'),
  createBaseElement('Escape from reality', 'theme', 152, 'Avoiding problems through retreat.'),
  createBaseElement('Brother-sister business', 'relationship', 152, 'Siblings as partners.'),
  createBaseElement('Taking refuge', 'beat', 152, 'Fleeing to safe space.'),

  // GONE GIRL - The shed
  createBaseElement('Incriminating evidence', 'emotions', 153, 'Horror at finding planted proof.'),
  createBaseElement('Hidden cache', 'story-particles', 153, 'Secrets tucked away.'),
  createBaseElement('Damning discovery', 'characteristics', 153, 'Proof of guilt appearing.'),
  createBaseElement('Evidence planted', 'tropes', 153, 'Frame-up made material.'),
  createBaseElement('Dusty enclosed air', 'sensory', 153, 'Stale space holding secrets.'),
  createBaseElement('Discovering the frame', 'momentum', 153, 'Finding evidence of setup.'),
  createBaseElement('Truth can be manufactured', 'theme', 153, 'Reality created by placement.'),
  createBaseElement('Victim and planted evidence', 'relationship', 153, 'Frame made physical.'),
  createBaseElement('Finding the purchases', 'beat', 153, 'Discovery of evidence.'),

  // GONE GIRL - Diary
  createBaseElement('False narrative', 'emotions', 154, 'Lies written as truth.'),
  createBaseElement('Fabricated confession', 'story-particles', 154, 'Made-up history in writing.'),
  createBaseElement('Deceptive testimony', 'characteristics', 154, 'Fiction posing as fact.'),
  createBaseElement('Unreliable narrator', 'tropes', 154, 'Written lies seeming true.'),
  createBaseElement('Page whisper-turning', 'sensory', 154, 'Reading invented past.'),
  createBaseElement('Crafting false history', 'momentum', 154, 'Creating fake evidence.'),
  createBaseElement('Truth is constructed', 'theme', 154, 'Narrative creating reality.'),
  createBaseElement('Writer and readers deceived', 'relationship', 154, 'False truth believed.'),
  createBaseElement('Reading the diary', 'beat', 154, 'Discovering the lies.'),

  // GONE GIRL - Treasure hunt clues
  createBaseElement('Nostalgic manipulation', 'emotions', 155, 'Memories weaponized.'),
  createBaseElement('Anniversary game twisted', 'story-particles', 155, 'Tradition turned trap.'),
  createBaseElement('Breadcrumb trail', 'characteristics', 155, 'Path leading to destruction.'),
  createBaseElement('Scavenger hunt', 'tropes', 155, 'Game with sinister purpose.'),
  createBaseElement('Paper texture familiar', 'sensory', 155, 'Recognizing her handwriting.'),
  createBaseElement('Following the path', 'momentum', 155, 'Walking into laid trap.'),
  createBaseElement('Love as manipulation', 'theme', 155, 'Intimacy weaponized.'),
  createBaseElement('Hunter and hunted spouse', 'relationship', 155, 'Partner leading to doom.'),
  createBaseElement('Finding each clue', 'beat', 155, 'Following breadcrumbs to trap.'),

  // GONE GIRL - Press conference
  createBaseElement('Performance anxiety', 'emotions', 156, 'Acting innocence under scrutiny.'),
  createBaseElement('Public declaration', 'story-particles', 156, 'Plea made to cameras.'),
  createBaseElement('Media spectacle', 'characteristics', 156, 'Private pain made public.'),
  createBaseElement('Public appeal', 'tropes', 156, 'Suspect pleading on TV.'),
  createBaseElement('Camera flash barrage', 'sensory', 156, 'Lights illuminating lies.'),
  createBaseElement('Performing for cameras', 'momentum', 156, 'Acting the part assigned.'),
  createBaseElement('Public perception is reality', 'theme', 156, 'How you appear becomes truth.'),
  createBaseElement('Accused and public', 'relationship', 156, 'Performance for judgment.'),
  createBaseElement('Going on television', 'beat', 156, 'Public plea for help.'),

  // GONE GIRL - Return home
  createBaseElement('Triumphant horror', 'emotions', 157, 'Victory revealing itself as trap.'),
  createBaseElement('Villain\'s return', 'story-particles', 157, 'Mastermind completing plan.'),
  createBaseElement('Calculated reappearance', 'characteristics', 157, 'Return perfectly timed.'),
  createBaseElement('The reveal', 'tropes', 157, 'Villain explaining their plan.'),
  createBaseElement('Door opening slowly', 'sensory', 157, 'Seeing her standing there.'),
  createBaseElement('Reappearing victorious', 'momentum', 157, 'Return as final move.'),
  createBaseElement('Trapped by appearances', 'theme', 157, 'Image becoming prison.'),
  createBaseElement('Captor and captive spouse', 'relationship', 157, 'Marriage as trap sprung.'),
  createBaseElement('She comes back', 'beat', 157, 'Return completing the plan.'),

  // GONE GIRL - Disappearance
  createBaseElement('Panic and confusion', 'emotions', 158, 'Chaos of sudden absence.'),
  createBaseElement('Vanishing act', 'story-particles', 158, 'Person erased without trace.'),
  createBaseElement('Mysterious absence', 'characteristics', 158, 'Gone without explanation.'),
  createBaseElement('Inciting disappearance', 'tropes', 158, 'Vanishing that starts mystery.'),
  createBaseElement('Silent empty house', 'sensory', 158, 'Absence louder than presence.'),
  createBaseElement('Searching for missing', 'momentum', 158, 'Looking for what\'s gone.'),
  createBaseElement('Absence speaks', 'theme', 158, 'What\'s missing revealing truth.'),
  createBaseElement('Searcher and missing', 'relationship', 158, 'Desperate hunt for vanished.'),
  createBaseElement('Discovering she\'s gone', 'beat', 158, 'Realizing absence.'),

  // GONE GIRL - Pregnancy reveal
  createBaseElement('Trapped realization', 'emotions', 159, 'New life as new prison.'),
  createBaseElement('Pregnancy announcement weapon', 'story-particles', 159, 'New life as control tool.'),
  createBaseElement('Biological trap', 'characteristics', 159, 'Life binding you forever.'),
  createBaseElement('Baby trap', 'tropes', 159, 'Pregnancy as permanent bond.'),
  createBaseElement('Test showing positive', 'sensory', 159, 'Lines appearing, fate sealing.'),
  createBaseElement('Announcing pregnancy', 'momentum', 159, 'News changing everything.'),
  createBaseElement('Parenthood as prison', 'theme', 159, 'Child binding toxic bond.'),
  createBaseElement('Parents forever linked', 'relationship', 159, 'Child connecting enemies.'),
  createBaseElement('Showing the test', 'beat', 159, 'Revealing the pregnancy.'),
];

// Helper to get elements by system
export function getElementsBySystem(system: SystemType): Element[] {
  return BASE_ELEMENTS.filter((el) => el.system === system);
}

// Helper to find element by ID
export function findElementById(id: string, allElements: Element[]): Element | undefined {
  return allElements.find((el) => el.id === id);
}
